apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: os-dev
  labels:
    app: os-dev
spec:
  version: 7.17.0
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
  - name: movie
    count: 1    
    config:
      node.store.allow_mmap: false